### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by gdkrmr** [linxihui/NNLM#1]
CRAN says that NNLM got archived, are you going to put it back on CRAN?

**Comment by linxihui** [comment]
Hi Guido,

There was a warning in version 0.4.1 (it was removed from CRAN and
archived)  and I am fixing it by submitting a version 0.4.2. I don't know
exactly how I should do this.  Should I fix 0.4.1 by re-submit the same
version (0.4.1) or a new version and ignore the warning in version 0.4.1?
Is updating a package the same as submitting a new package?

Thanks,

Eric

**Comment by gdkrmr** [comment]
I think that simply submitting version 0.4.2 will be fine, just make a comment that you fixed the warnings.

**Comment by ttriche** [comment]
bump the package version and resubmit.  NNLM is fantastic, would be tragic
for it to go away.

--t

**Comment by topepo** [comment]
Is there anything that I can do to help get this back on CRAN? If you need some guidance on the submitting process, I'd be happy to help out. 

If you haven't done it in a while, I suggest running `R CMD check --as-cran` on the current version of R and pasting the output in the notes section of the submission.

This is a lot easier if you use the `devtools` package. It also contains a function that will do a test submission to a server that is much closer to the process that CRAN uses to check packages.

**Comment by gdkrmr** [comment]
any news, or at least a statement that you will not support this package any more?

**Comment by linxihui** [comment]
@gdkrmr @topepo   I submitted 0.4.2 to CRAN, but it is still complaining the 0.4.1 warning issue. Seems like I have to do a 0.4.1 submission to fix the issue instead of a new version. Do you know anything about it?  I don't know what to do exactly. 
BTW, I am using devtools, just the way of submission/update to CRAN confuses me.

**Comment by gdkrmr** [comment]
I don't think that this is the case, if the warning is the same as 0.4.1 then you probably did not fix it ;-)

**Comment by gdkrmr** [comment]
does it give a warning on your own machine?

**Comment by linxihui** [comment]
@gdkrmr No warning.  There is only a NOTE saying the previous version is archived.

**Comment by linxihui** [comment]
@gdkrmr  I was giving a link to confirm the submission of version 0.4.2, and one of the checkboxes is 
"I have fixed all problems shown on the[ package check page](http://cran.r-project.org/web/checks/check_results_NNLM.html)." But the link shows the building error of previous version (0.4.1).

**Comment by topepo** [comment]
You should also look at the `build_win` function in `devtools`. The package maintainer can submit their package to an internal testing server that CRAN uses to get the most real sense of what might get flagged. It's not perfect but helps a lot. Just don't overwhelm them with submissions.

**Comment by gdkrmr** [comment]
looking at the warning in your link, it looks like the method did not converge, did you try more iterations?

**Comment by linxihui** [comment]
@gdkrmr  @topepo  FYI, the package is now on CRAN again.

**Comment by ttriche** [comment]
you're a hero

thanks!

--t

**Comment by gdkrmr** [comment]
ok, great!
