### ISSUE TITLE
Invalid URL for the vignette on the README

### ISSUE THREAD

**Issue by JiaxiangBU** [linxihui/NNLM#10]
The invalid URL of the vignette on CRAN
https://cran.r-project.org/web/packages/NNLM/vignettes/Fast-And-Versatile-NMF.html

**Comment by linxihui** [comment]
Updated. Thanks for pointing it out.

**Comment by JiaxiangBU** [comment]
Thanks, it works.
https://cran.r-project.org/web/packages/NNLM/vignettes/Fast-And-Versatile-NMF.pdf
