### ISSUE TITLE
unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by MariaCartolano** [linxihui/NNLM#13]
Hello,

I am trying to install NNLM on a macOS HighSierra but I get the following compiling error:

clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘NNLM’
* removing ‘/Users/mcartolano/Library/R/3.5/library/NNLM’
Error: Failed to install 'NNLM' from GitHub:
  (converted from warning) installation of package ‘/var/folders/zn/xpbs565x65l5lspg7_ww9p5c0000gp/T//RtmpzGUbQv/file3a1f6d465dec/NNLM_0.4.4.tar.gz’ had non-zero exit status

I have done a bit of research and what I have understood is that clang does not support openMP.
An alternative would be to overwrite clang with gcc or g++. However, this is not my preferred option because I have a few things that I am developing right now in C++ and they compile just fine. In a nutshell I am afraid to mess up.

Do you guys have other , less intrusive, suggestions on how to overcome this problem?

cheers

**Comment by pmquiros** [comment]
I had the same problem and I solved it by following this comment:

https://github.com/velocyto-team/velocyto.R/issues/57#issuecomment-506671728

**Comment by MariaCartolano** [comment]
Hi thanks,
I actually found this that also worked for me:
https://thecoatlessprofessor.com/programming/cpp/openmp-in-r-on-os-x/
It is a clang version compatible with openMP. It worked really quick!
cheers
