### ISSUE TITLE
nnmf: k larger than 0 is not recommended

### ISSUE THREAD

**Issue by IdelCoder** [linxihui/NNLM#2]
I have no idea what it means. The document [https://cran.r-project.org/web/packages/NNLM/vignettes/Fast-And-Versatile-NMF.html#missing-value-imputation-and-application-in-recommendation-system] says the k is the rank of NMF. Can I think of it as the dimension that W and H shares?

<img width="416" alt="error" src="https://user-images.githubusercontent.com/28784141/43116042-707d499e-8f38-11e8-942b-390277fc3dd7.png">

**Comment by linxihui** [comment]
@IdelCoder 
Maybe check your matrix `mymatrix`, it might have a row or a column almost full of `NA`.  Here it how it works
https://github.com/linxihui/NNLM/blob/master/R/nnmf.R#L161
```r
min.k <- min(dim(A));
A.isNA <- is.na(A);
A.anyNA <- any(A.isNA); # anyNA is depreciated in new version of R
if (A.anyNA) {
	min.k <- min(min.k, ncol(A) - rowSums(A.isNA), nrow(A) - colSums(A.isNA));
	}
min.k <- min(min.k, ncol(A) - rowSums(A.isNA), nrow(A) - colSums(A.isNA));
```
