### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by maryam1717** [linxihui/NNLM#22]
Dear NNLM team,

I'm trying to install the NNLM package in R and I got this error:
 #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
I don't know how to fix this problem. any recommendation or solution will be appreciated.

**Comment by zdebruine** [comment]
Works for me, I'm using C++11 and the newest version of Armadillo, loaded with RcppArmadillo

This is not an NNLM issue, it's an issue with your session and/or installed libraries.

**Comment by linxihui** [comment]
@zdebruine  Thanks for the answer.
@maryam1717, the issue is probably raised by Armadillo. You need to make sure you have a compiler supporting C++11 on your machine.
