### ISSUE TITLE
Running into ld error while installing NNLM

### ISSUE THREAD

**Issue by hanchangxi** [linxihui/NNLM#30]
Hello, I ran into the following error  while installing NNLM packages. It seems that R couldn't find those files. I have tried to add the exact path to the Environment Variable. But that still could not be solved. I'm asking for your help gently. Thanks.

g++ -std=gnu++17 -shared -s -static-libgcc -o NNLM.dll tmp.def RcppExports.o base_algorithms.o nnlm.o nnmf.o update_with_missing.o -fopenmp -LD:/software/R-4.3.1/bin/x64 -lRlapack -LD:/software/R-4.3.1/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/RBuildTools/4.3/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/RBuildTools/4.3/x86_64-w64-mingw32.static.posix/lib -LD:/software/R-4.3.1/bin/x64 -lR
C:\RBuildTools\4.3\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lRlapack: No such file or directory
C:\RBuildTools\4.3\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lRblas: No such file or directory
C:\RBuildTools\4.3\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lR: No such file or directory
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'NNLM'

**Comment by hanchangxi** [comment]
By the way, the version of R I use is 4.3.1. Dose that really matter? I noticed that this pakcage was not recommended to be installed in R of 4.0.0.

**Comment by nroak** [comment]
I was facing the same issue, installing RcppArmadillo package solved the isssue for me.
I also updated ~/.R/Makevars file to include my gcc path `FLIBS=-L/usr/local/Cellar/gcc/13.2.0/lib/gcc/13.2.0`
