### ISSUE TITLE
Extracting Scores and estimating number of factors

### ISSUE THREAD

**Issue by gufranca** [linxihui/NNLM#7]
Hi

I found NNLM an extremely useful tool to find metagene signatures in gene expression data. I was also trying to use the NMF package, which provides extractFeatures() and featureScore() functions to obtain and filter important features for each factor. I was wondering, is there is any similar functions in NNLM for better gene (feature) and metagene selection? I was wondering if there is also some function to help estimating the best number of factors (k)?

I appreciate any help
Gustavo

**Comment by linxihui** [comment]
@gufranca 
Currently, I have no plan to implement feature scoring. But it should be straight forward after getting the decomposition.
For determine `k`,  you can read the paper [here](https://www.biorxiv.org/content/10.1101/321802v1) for detail, or code example [here](https://www.biorxiv.org/content/10.1101/321802v1) (the last part). There is not a single function does the work now, but I might do it in the future.
