### ISSUE TITLE
NNLM removed from CRAN

### ISSUE THREAD

**Issue by tomwenseleers** [linxihui/NNLM#8]
CRAN now mentions that NNLM has been removed, saying "Archived on 2019-04-22 as check errors were not corrected despite reminders." - you might like to fix this...

**Comment by SaskiaFreytag** [comment]
When I tried installing the achieved version I unfortunately got the following error:

> /usr/local/opt/llvm/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found

**Comment by linxihui** [comment]
@tomwenseleers @SaskiaFreytag  Back to CRAN now. Sorry for the way.  BTW, you can always use `devtools::install_github` to install directly from this Github.

**Comment by SaskiaFreytag** [comment]
yeah i tried that at the time and I got the same error as described above. but great work that it is back. thank you!
